repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
      exclude: invalidFile.yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
      args: ['--maxkb=800']
    - id: check-json
      types: [text]
      files: \.(json|config)$
      exclude: '(invalidFile.json|SkipValidationsTemplates.json|tsconfig.json|nuget.config)$'
    - id: pretty-format-json
      args:
          - "--autofix"
          - "--indent=4"
          - "--no-sort-keys"
      types: [text]
      files: \.(json|config)$
      exclude: '(invalidFile.json|SkipValidationsTemplates.json|tsconfig.json|nuget.config)$'
    - id: detect-private-key
    - id: check-case-conflict
    - id: requirements-txt-fixer
