---

name: PSRule validation
on:
  push:
  pull_request:

jobs:
  analyze_arm:
    name: Analyze ARM templates
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Analyze Azure template files
      uses: microsoft/ps-rule@v2.7.0
      with:
        modules: 'PSRule.Rules.Azure'
      continue-on-error: true
